version: '3.7'

services:
  
  node:
    container_name: spoc
    image: cmh1506/spoc
    environment:
      - ENV="docker"
    build:
      context: .
      dockerfile: node.dockerfile      
    ports:
      - "3000:3000"
    networks:
      - spoc-network
    depends_on: 
      - mongodb  
  mongodb:
    container_name: mongodb
    build:
      context: .
      dockerfile: mongo.dockerfile
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - spoc-network
volumes:
  mongodb:
networks:
  spoc-network:
    driver: bridge