version: '3.7'

services:

  node:
    container_name: spoc
    image: cmh1506/spoc
    build:
      context: .
      dockerfile: node.dockerfile      
    ports:
      - "3000:3000"
    networks:
      - spoc-network
    volumes:
      - ./logs:/var/www/logs
    depends_on: 
      - mongodb
      
  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - spoc-network

networks:
  spoc-network:
    driver: bridge